# Generated by Django 5.0 on 2025-09-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_extractor', '0002_group_groupmember_delete_groupnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_extractor.group'),
        ),
    ]
